### PR TITLE
rollup to cjs

### PR DESCRIPTION
**Pull request by isimisi**
couldn't use this package in commonJS - this pr will rollup the package to cjs so that it bot can be imported and required

added in order to make sure single standalone spaces are included 
```js
   fillText(text, x, y, maxWidth, fontSize) {
      if (!text || (!text.length === 1 && text.trim().length < 1)) return;
```

(also had to verify commit, so closed the other pr)

### CODE REVIEW

**Comment by Keanottesen** [comment]
Would be good to merge!!

**Comment by Luis-Sejer** [comment]
# Lifesaver! ❗ 💯 🦁

**Comment by apperside** [comment]
this should be merged!

**Comment by victorsc** [comment]
Thanks for merging this @modesty 
Could you also create a new release?
Thank you!

**Comment by modesty** [comment]
v3.0.5 released

**Pull request merged**
